version: 2
sources:
  - name: bronze
    schema: bronze
    tables:
      # Clima
      - name: bronze_estaciones_agrocabildo
      - name: bronze_clima_horario_agrocabildo
      - name: bronze_sensores_meteorologicos
      
      # Espacial
      - name: bronze_h3_grid
      - name: bronze_espacios_naturales
      - name: bronze_mdt_stats
      - name: bronze_satelite_stats
      - name: bronze_limites_municipales
      - name: bronze_zonas_turisticas
      - name: bronze_osm_pois
      - name: bronze_bienes_interes_cultural
      - name: bronze_oficinas_turismo
      
      # Movilidad
      - name: bronze_gtfs_paradas
      - name: bronze_gtfs_rutas
      - name: bronze_gtfs_rutas_atributos
      - name: bronze_gtfs_viajes
      - name: bronze_gtfs_calendario
      - name: bronze_gtfs_calendario_excepciones
      - name: bronze_gtfs_horarios
      
      # Plataformas y Alojamiento (Nuevas incorporaciones)
      - name: bronze_aena_pasajeros
      - name: bronze_booking_establishments
      - name: bronze_booking_reviews
      - name: bronze_booking_geocoding_lookup
      - name: bronze_registro_extrahoteleros
      - name: bronze_registro_hoteles
      - name: bronze_registro_viviendas_vacacionales
      - name: bronze_registro_geocoding_lookup
      
      # NLP / Redes Sociales
      - name: bronze_youtube_videos
      - name: bronze_youtube_comments
      - name: bronze_losviajeros_temas
      - name: bronze_losviajeros_mensajes
      - name: bronze_tripadvisor_resenas
      - name: bronze_tripadvisor_ubicaciones
      - name: bronze_ml_sentiment_results
      - name: bronze_ml_aspect_results

      # ISTAC - Demografía y Paro
      - name: bronze_istac_mun_edad_media
      - name: bronze_istac_mun_paro_registrado
      - name: bronze_istac_mun_poblacion_15_64
      - name: bronze_istac_mun_poblacion_65_mas
      - name: bronze_istac_mun_poblacion_total
      
      # ISTAC - Suite Completa de Empleo y Seguridad Social
      - name: bronze_istac_mun_empleo_total
      - name: bronze_istac_mun_empleo_asalariados
      - name: bronze_istac_mun_empleo_autonomos
      - name: bronze_istac_mun_empleo_hosteleria
      - name: bronze_istac_mun_empleo_servicios
      - name: bronze_istac_mun_empleo_comercio
      - name: bronze_istac_mun_empleo_construccion
      - name: bronze_istac_mun_empleo_industria
      - name: bronze_istac_mun_empleo_agricultura

      # ISTAC - Vivienda Vacacional
      - name: bronze_istac_mun_alojamientos_abiertos_vv
      - name: bronze_istac_mun_estancia_media_vv
      - name: bronze_istac_mun_ingresos_vv
      - name: bronze_istac_mun_plazas_vv
      - name: bronze_istac_mun_tasa_ocupacion_vv

      # ISTAC - Turismo Hotelero EOH
      - name: bronze_istac_mun_pernoctaciones
      - name: bronze_istac_mun_plazas_ofertadas
      - name: bronze_istac_mun_pob_turistica_equiv
      - name: bronze_istac_mun_tasa_ocupacion_plazas
      - name: bronze_istac_mun_viajeros_entrados